<?xml version="1.0" ?>
<testCase duration="0.059" fail="1" name="SET-187" pass="0" startdate="20160215" starttime="143944">
	<block fail="0" pass="0"/>
	<block fail="1" pass="0">
		<call fail="1" pass="0">functions.raiseError('Intentional exception in setup phase')</call>
	</block>
	<block fail="0" pass="0">
		<call fail="0" pass="0">functions.raiseError('Execution phase should not be executed')</call>
	</block>
	<block fail="0" pass="0"/>
</testCase>
