<?xml version="1.0" ?>
<testCase duration="0.060" fail="1" name="SET-222" pass="0" startdate="20160215" starttime="150629">
	<block fail="0" pass="0"/>
	<block fail="0" pass="0"/>
	<block fail="1" pass="0">
		<block fail="1" pass="0">
			<call fail="1" pass="0">functions.raiseError('Intentional exception in execution phase')</call>
		</block>
		<block fail="0" pass="1">
			<call fail="0" pass="1">functions.addValues(vars.a, &quot;C&quot;)</call>
		</block>
		<block fail="0" pass="0">
			<call fail="0" pass="1">functions.addValues(vars.a, &quot;A&quot;)</call>
		</block>
	</block>
	<block fail="0" pass="1">
		<call fail="0" pass="1">functions.compareValues(vars.a, &quot;AC&quot;)</call>
	</block>
</testCase>
